# permissions for end users to edit jannahs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jannah-editor-role
rules:
- apiGroups:
  - jannah.jannah.io
  resources:
  - jannahs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jannah.jannah.io
  resources:
  - jannahs/status
  verbs:
  - get
