# permissions for end users to view jannahs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jannah-viewer-role
rules:
- apiGroups:
  - jannah.jannah.io
  resources:
  - jannahs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jannah.jannah.io
  resources:
  - jannahs/status
  verbs:
  - get
